# Generated by Django 3.0.5 on 2023-07-07 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0012_staff_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_leave',
            new_name='StaffLeave',
        ),
    ]
